TodoWeb/Models/Todo.cs
using System.ComponentModel.DataAnnotations;

namespace TodoWeb.Models
{
    public class Todo
    {
        [Key]
        public int Note_id { get; set; }

        public string? Title { get; set; }

        public string? Description { get; set; }

        public DateTime CreatedAt { get; set; }
        
        public DateTime UpdatedAt { get; set; }

        public bool IsCompleted { get; set; }

        public Category Category { get; set; }

        public User User { get; set; }
    }
}

TodoWeb/Controllers/TodoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using TodoWeb.Data;
using TodoWeb.Models;
using TodoWeb.TodoVM;

namespace TodoWeb.Controllers
{
    [Authorize]
    public class TodoController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<User> _userManager;

        public TodoController(UserManager<User>userManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(int catId)
        {
            var userLog = await _userManager.GetUserAsync(User);

            var todoQuery = await _context.Todos
                .Where(todo => todo.User.Id == userLog.Id)
                .Include(category => category.Category)
                .Include(user => user.User)
                .OrderByDescending(update => update.UpdatedAt)
                .ToListAsync();

            var todoCategory = await _context.Category.ToListAsync();

            if (todoQuery == null)
            {
                return NotFound();
            }

            if (catId != 0)
            {
                todoQuery = todoQuery.Where(cat => cat.Category.Category_id == catId).ToList();
            }
            var todoVm = new TodoViewModel
            {
                Todoes = todoQuery,
                Categories = new SelectList(todoCategory, "Category_id", "Category_name"),
                Category_note_id = catId
            };
            return View(todoVm);
        }

        public async Task<IActionResult> Create()
        {
            var todoCategory = await _context.Category.ToListAsync();
            var todoVM = new TodoViewModel
            {
                TodoSingle = new Todo(),
                Categories = new SelectList(todoCategory, "Category_id", "Category_name")
            };
            return View(todoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTodo(TodoViewModel todoObj)
        {
            var selectedCategoryName = await Utils.Utils.GetCategoryAsync(_context, todoObj.TodoSingle.Category.Category_id);

            var user = await _userManager.GetUserAsync(User);

            var inputTodo = new Todo
            {
                User = user,
                Title = todoObj.TodoSingle.Title,
                Description = todoObj.TodoSingle.Description,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
                IsCompleted = todoObj.TodoSingle.IsCompleted,
                Category = selectedCategoryName,
            };
            _context.Todos.Add(inputTodo);
            await _context.SaveChangesAsync();
            TempData["success"] = "Todo successfully created";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var todo = _context.Todos.Find(id);
            if (todo == null)
            {
                return NotFound();
            }
            var todoCategory = await _context.Category.ToListAsync();
            var todoVm = new TodoViewModel
            {
                Categories = new SelectList(todoCategory,"Category_id", "Category_name"),
                Note_id = todo.Note_id,
                Note_title = todo.Title,
                Note_description = todo.Description,
                Note_completed = todo.IsCompleted,
                Category_note_id = todo.Category.Category_id
            };
            return View(todoVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTodo(TodoViewModel todoUpdt)
        {
            var selectedCategory = await Utils.Utils.GetCategoryAsync(_context, todoUpdt.Category_note_id);
            var todo = await _context.Todos.FindAsync(todoUpdt.Note_id);
            if (todo == null) 
            { 
                return NotFound();
            }
            todo.Note_id = todoUpdt.Note_id;
            todo.Title = todoUpdt.Note_title;
            todo.Description = todoUpdt.Note_description;
            todo.UpdatedAt = DateTime.UtcNow;
            todo.IsCompleted = todoUpdt.Note_completed;
            todo.Category = selectedCategory;

            await _context.SaveChangesAsync();
            TempData["success"] = "Todo successfully Updated";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetDeleteData(int? id)
        {
            if(id == null)
            {
                return NotFound(); 
            }
            var todoItem = await _context.Todos.FindAsync(id);
            if (todoItem == null)
            {
                return NotFound();
            }
            return Json(todoItem);
        }

        public async Task<IActionResult> DeleteTodo(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var todoItem = await _context.Todos.FindAsync(id);
            if (todoItem == null) { 
                return NotFound();
            }
            _context.Todos.Remove(todoItem);
            await _context.SaveChangesAsync();
            TempData["success"] = "Todo successfully deleted";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> FilterTodo(int? categoriesValue)
        {
            var userLog = await _userManager.GetUserAsync(User);
            var todoCategory = await _context.Category.ToListAsync();

            var todoQuery = await _context.Todos
                .Where(todo => todo.User.Id == userLog.Id)
                .Where(cat => cat.Category.Category_id == categoriesValue)
                .Include(category => category.Category)
                .Include(user => user.User)
                .OrderByDescending(update => update.UpdatedAt)
                .ToListAsync();

            var todoVm = new TodoViewModel
            {
                Todoes = todoQuery,
                Categories = new SelectList(todoCategory, "Category_id", "Category_name")
            };

            return RedirectToAction("Index", todoVm);
        }
    }
}

TodoWeb/Views/Todo/Create.cshtml
@model TodoWeb.TodoVM.TodoViewModel;
@{
    ViewData["Title"] = "Create";
}
<form method="post" asp-action="CreateTodo">
    <div class="row">
        <div class="d-flex flex-column input-group col">
            <textarea id="input-title" asp-for="TodoSingle.Title" class="input-form form-title mb-2" type="text" placeholder="Title" oninput="input_change()"></textarea>
            <textarea id="input-body" asp-for="TodoSingle.Description" class="input-form form-body" type="text" placeholder="Body" oninput="input_change()"></textarea>
        </div>
        <div class="col-3">
            <h5 class="category-title mb-4">Category</h5>
            <select id="select-category" class="form-select" asp-for="TodoSingle.Category.Category_id" asp-items="Model.Categories" onchange="catChange()"></select>
        </div>

    </div>
    <button type="submit" class="btn bg-warning rounded-circle button-create" id="button_add">
        <i class="bi bi-pencil-square"></i>
    </button>
</form>

TodoWeb/Views/Todo/Index.cshtml
@model TodoWeb.TodoVM.TodoViewModel
@{
    ViewData["Title"] = "Todo Home";
}

<partial name="_ModalAlert"/>
<partial name="_SwalSuccess"/>

<h1 class="my-5 title-head">Todo</h1>
<div class="d-flex justify-content-center my-5">
    <div>
        <form asp-controller="Todo" asp-action="Index" method="get">
            <label for="category-filter" class="mb-2">Filter by: </label>
            <div class="d-flex gap-2">
                <select id="category-filter" name="catId" class="form-select" asp-items="Model.Categories" value="@Model.Category_note_id">
                    <option value=0>All</option>
                </select>
                <button type="submit" class="btn btn-primary"><i class="bi bi-funnel"></i></button>
            </div>
        </form>
    </div>
</div>
<div class="row row-cols-5 gap-4"> 
    @foreach(var todo in Model.Todoes)
    {
        <div class="sticky-notes p-4 d-flex flex-column rounded-5 ">
            @if (todo.IsCompleted)
            {
                <div class="todo-status rounded-circle bg-success">
                    <i class="bi bi-check-all"></i>
                </div>
            }
            <h5 class="">@todo.Title</h5>
            <p class="m-0 description">@todo.Description</p>
            <div class="mt-auto d-flex align-items-lg-center justify-content-between">
                <p class="rounded-1 bg-success m-0 px-3 category-tag">@todo.Category.Category_name</p>
                <div class="group-btn">
                    <button class="btn-act p-1" type="button" data-bs-toggle="modal" data-bs-target="#alertModal" onclick="oldValue(@todo.Note_id)">
                        <i class="bi bi-trash2"></i>
                    </button>
                    <a class="btn-act p-1" asp-controller="Todo" asp-action="Update" asp-route-id="@todo.Note_id">
                        <i class="bi bi-pencil"></i>
                    </a>
                </div>
            </div>
            <div class="d-flex justify-content-between">
            <p class="m-0 time-notes text-end">@todo.UpdatedAt.ToString("dd/MM/yyyy")</p>
            <p class="m-0 time-notes text-end">@todo.UpdatedAt.ToString("HH:mm")</p>
            </div>
        </div>
    }
</div>

<a class="bg-warning rounded-circle button-add" asp-controller="Todo" asp-action="Create">
    <i class="bi bi-pencil-square"></i>
</a>

<script>
    function oldValue(id){
        $.ajax({
            url : '@Url.Action("GetDeleteData")',
            type : "GET",
            data: {id : id},
            success: function (data) {
                console.log(data);
                $('#todo-item').val(data.note_id);
            }
        });
    };
</script>

TodoWeb/Views/Todo/Update.cshtml
@model TodoWeb.TodoVM.TodoViewModel;

@{
    ViewData["Title"] = "Update";
}

<form method="post" asp-action="UpdateTodo">
    <div class="row">
        <div class="d-flex flex-column input-group col">
            <input type="hidden" value="@Model.Note_id" asp-for="@Model.Note_id" />
            <textarea id="input-title" asp-for="@Model.Note_title" class="input-form form-title mb-2" type="text" placeholder="Title" oninput="input_change()"></textarea>
            <textarea id="input-body" asp-for="@Model.Note_description" class="input-form form-body" type="text" placeholder="Body" oninput="input_change()"></textarea>
        </div>
        <div class="col-3">
            <h5 class="category-title mb-4">Category</h5>
            <select id="select-category" class="form-select" asp-for="@Model.Category_note_id" asp-items="Model.Categories" value="@Model.Category_note_id" onchange="catChange()"></select>
            <div class="form-check my-2">
                <input class="form-check-input" type="checkbox" id="flexCheckDefault" asp-for="@Model.Note_completed">
                <label class="form-check-label" for="flexCheckDefault">
                    Completed
                </label>
            </div>
        </div>
    </div>

    <button type="submit" class="btn bg-warning rounded-circle button-create" id="button_add">
        <i class="bi bi-pencil-square"></i>
    </button>
</form>
<script>
    const checkbox = document.getElementById('flexCheckDefault');
    checkbox.addEventListener('change', function () {
        checkbox.value = checkbox.checked ? 'true' : 'false';
        button_add.classList.add("button-translate");
        button_add.classList.remove("button-create");
        console.log(checkbox.value);
    })
    @Model.Note_completed ? checkbox.checked : checkbox.unchecked;
</script>